name:                aoc-2k21
version:             0.1.0.0
github:              "anihm136/aoc-2k21"
license:             MIT
author:              "Anirudh H M"
maintainer:          "anihm136@gmail.com"
copyright:           "2022 Anirudh H M"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/anihm136/aoc-2k21#readme>

dependencies:
- base >= 4.7 && < 5
- split
- containers
- array

library:
  source-dirs: src

executables:
  aoc-2k21-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc-2k21

tests:
  aoc-2k21-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc-2k21
